# Opens pull requests when dependencies have updates, including security fixes.
version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      androidx:
        patterns: ["androidx.*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
